config/routes.rb
Rails.application.routes.draw do
  resources :blocks
  root 'blocks#index'
end

app/models/block.rb
class Block < ActiveRecord::Base

  validates :name,
    presence: { message: "入力してください" },
    length: { minimum: 3, message: "短すぎ！" }
  validates :memo, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController

  before_action :set_block, only: [:show, :edit, :update, :destroy]

  def index
    @blocks = Block.all
  end

  def show
  end

  def new
    @block = Block.new
  end

  def create
    @block = Block.new(block_params)
    if @block.save
      redirect_to blocks_path
    else
      render 'new'
    end
  end

  def edit
  end
 
  def update
    if @block.update(block_params)
      redirect_to blocks_path
    else
      render 'edit'
    end
  end

  def destroy
    @block.destroy
    redirect_to blocks_path
  end

  private def block_params
    params[:block].permit(:name, :memo)
  end

  def set_block
    @block = Block.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<%= form_for @block do |f| %>
  <p>
    <%= f.label :name %> <%= f.text_field :name %> <br />
    <% if @block.errors.any? %>
      <%= @block.errors.messages[:name][0] %>
    <% end %>
    <%= f.label :memo %> <%= f.text_field :memo %> <br />
    <% if @block.errors.any? %>
      <%= @block.errors.messages[:memo][0] %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <p>
    --- for debug ------------------------<br />
    <%= @block.inspect %><br />
    <%= @block.errors.inspect %><br />
    -------------------------------------------<br />
  </p>
<% end %>

app/views/blocks/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/blocks/index.html.erb
<h1>Blocks</h1>

<ul>
  <% @blocks.each do |block| %>
    <li>
      <%= link_to block.name, block_path(block.id) %>
      <%= link_to "[edit]", edit_block_path(block.id) %>
      <%= link_to "[del]", block_path(block.id), method: :delete, data: { confirm: "are you sure?" } %>
    </li>
  <% end %>
</ul>

<p><%= link_to "Add New", new_block_path %></p>

app/views/blocks/new.html.erb
<h1>Add New</h1>

<%= render 'form' %>

app/views/blocks/show.html.erb
<h1><%= @block.name %></h1>

<div>
  <%= @block.memo %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= image_tag "logo.png" %>
 
<%= yield %>
 
<%= link_to "Home", blocks_path %>

</body>
</html>